In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns

In [ ]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [ ]:
df=sns.load_dataset('taxis')
df

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6428,2019-03-31 09:51:53,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,6.36,green,credit card,East Harlem North,Central Harlem North,Manhattan,Manhattan
6429,2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,58.80,green,credit card,Jamaica,East Concourse/Concourse Village,Queens,Bronx
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.0,0.00,0.0,17.30,green,cash,Crown Heights North,Bushwick North,Brooklyn,Brooklyn
6431,2019-03-04 10:09:25,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,6.80,green,credit card,East New York,East Flatbush/Remsen Village,Brooklyn,Brooklyn
6432,2019-03-13 19:31:22,2019-03-13 19:48:02,1,3.85,15.0,3.36,0.0,20.16,green,credit card,Boerum Hill,Windsor Terrace,Brooklyn,Brooklyn

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6433 entries, 0 to 6432
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   pickup           6433 non-null   datetime64[ns]
 1   dropoff          6433 non-null   datetime64[ns]
 2   passengers       6433 non-null   int64
 3   distance         6433 non-null   float64
 4   fare             6433 non-null   float64
 5   tip              6433 non-null   float64
 6   tolls            6433 non-null   float64
 7   total            6433 non-null   float64
 8   color            6433 non-null   object
 9   payment          6389 non-null   object
 10  pickup_zone      6407 non-null   object
 11  dropoff_zone     6388 non-null   object
 12  pickup_borough   6407 non-null   object
 13  dropoff_borough  6388 non-null   object
dtypes: datetime64[ns](2), float64(5), int64(1), object(6)
memory usage: 703.7+ KB

In [ ]:
df.sample(10)

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
1163,2019-03-08 11:05:04,2019-03-08 11:14:23,1,1.10,7.5,2.16,0.0,12.96,yellow,credit card,Penn Station/Madison Sq West,Union Sq,Manhattan,Manhattan
2964,2019-03-12 16:04:44,2019-03-12 16:54:36,1,9.60,36.0,0.00,0.0,36.80,yellow,credit card,LaGuardia Airport,Crown Heights North,Queens,Brooklyn
1197,2019-03-19 23:16:03,2019-03-19 23:20:14,1,0.60,5.0,1.75,0.0,10.55,yellow,credit card,Gramercy,Kips Bay,Manhattan,Manhattan
6073,2019-03-06 10:08:03,2019-03-06 10:12:22,1,0.69,5.0,0.00,0.0,5.80,green,cash,Morningside Heights,Morningside Heights,Manhattan,Manhattan
733,2019-03-13 12:11:35,2019-03-13 12:24:33,2,1.90,10.0,2.00,0.0,15.30,yellow,credit card,Manhattan Valley,Upper East Side North,Manhattan,Manhattan
4812,2019-03-12 18:34:19,2019-03-12 18:37:12,1,0.60,4.5,1.75,0.0,10.55,yellow,credit card,Upper West Side North,Manhattan Valley,Manhattan,Manhattan
3837,2019-03-04 06:06:45,2019-03-04 06:15:16,1,2.40,9.5,2.55,0.0,15.35,yellow,credit card,Clinton East,Lenox Hill West,Manhattan,Manhattan
5999,2019-03-12 21:07:48,2019-03-12 21:17:50,1,1.87,9.0,0.00,0.0,10.30,green,cash,Elmhurst,Jackson Heights,Queens,Queens
3789,2019-03-19 06:38:48,2019-03-19 06:47:41,1,1.81,8.5,2.36,0.0,14.16,yellow,credit card,Kips Bay,Greenwich Village North,Manhattan,Manhattan
4399,2019-03-18 18:50:37,2019-03-18 19:09:51,1,3.10,14.5,4.70,0.0,23.50,yellow,credit card,Seaport,Union Sq,Manhattan,Manhattan

In [ ]:
df.sample(5)

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
966,2019-03-23 11:59:53,2019-03-23 12:16:28,2,3.78,14.50,3.56,0.0,21.36,yellow,credit card,Yorkville East,Times Sq/Theatre District,Manhattan,Manhattan
2064,2019-03-05 22:04:53,2019-03-05 22:12:22,5,2.35,9.00,2.46,0.0,14.76,yellow,credit card,Upper East Side South,Manhattan Valley,Manhattan,Manhattan
6219,2019-03-20 09:04:16,2019-03-20 09:24:04,1,5.30,18.68,0.00,0.0,19.18,green,credit card,Highbridge,Norwood,Bronx,Bronx
5230,2019-03-19 16:38:03,2019-03-19 16:44:34,1,1.07,6.50,0.00,0.0,8.30,yellow,credit card,East Harlem North,East Harlem South,Manhattan,Manhattan
6346,2019-03-19 12:29:29,2019-03-19 13:02:38,1,10.05,33.50,0.00,0.0,34.30,green,credit card,Mount Hope,Midtown North,Bronx,Manhattan

In [ ]:
df.tail(10) #showing last rows

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
6423,2019-03-12 08:10:47,2019-03-12 08:35:35,1,4.30,18.50,0.00,0.0,19.30,green,credit card,Saint Albans,Hillcrest/Pomonok,Queens,Queens
6424,2019-03-30 20:52:15,2019-03-30 20:59:55,1,1.70,8.00,0.00,0.0,9.30,green,cash,Central Harlem,Central Harlem North,Manhattan,Manhattan
6425,2019-03-07 15:34:30,2019-03-07 16:31:06,1,9.12,26.32,0.00,0.0,26.82,green,credit card,Park Slope,East New York,Brooklyn,Brooklyn
6426,2019-03-28 08:04:47,2019-03-28 08:07:46,1,0.71,4.50,0.50,0.0,5.80,green,credit card,Central Park,Upper West Side North,Manhattan,Manhattan
6427,2019-03-23 18:26:09,2019-03-23 18:49:12,1,7.07,20.00,0.00,0.0,20.00,green,cash,Parkchester,East Harlem South,Bronx,Manhattan
6428,2019-03-31 09:51:53,2019-03-31 09:55:27,1,0.75,4.50,1.06,0.0,6.36,green,credit card,East Harlem North,Central Harlem North,Manhattan,Manhattan
6429,2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.00,0.00,0.0,58.80,green,credit card,Jamaica,East Concourse/Concourse Village,Queens,Bronx
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.00,0.00,0.0,17.30,green,cash,Crown Heights North,Bushwick North,Brooklyn,Brooklyn
6431,2019-03-04 10:09:25,2019-03-04 10:14:29,1,1.12,6.00,0.00,0.0,6.80,green,credit card,East New York,East Flatbush/Remsen Village,Brooklyn,Brooklyn
6432,2019-03-13 19:31:22,2019-03-13 19:48:02,1,3.85,15.00,3.36,0.0,20.16,green,credit card,Boerum Hill,Windsor Terrace,Brooklyn,Brooklyn

In [ ]:
df.head(10) #showimg first rows

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan
5,2019-03-11 10:37:23,2019-03-11 10:47:31,1,0.49,7.5,2.16,0.0,12.96,yellow,credit card,Times Sq/Theatre District,Midtown East,Manhattan,Manhattan
6,2019-03-26 21:07:31,2019-03-26 21:17:29,1,3.65,13.0,2.00,0.0,18.80,yellow,credit card,Battery Park City,Two Bridges/Seward Park,Manhattan,Manhattan
7,2019-03-22 12:47:13,2019-03-22 12:58:17,0,1.40,8.5,0.00,0.0,11.80,yellow,NaN,Murray Hill,Flatiron,Manhattan,Manhattan
8,2019-03-23 11:48:50,2019-03-23 12:06:14,1,3.63,15.0,1.00,0.0,19.30,yellow,credit card,East Harlem South,Midtown Center,Manhattan,Manhattan
9,2019-03-08 16:18:37,2019-03-08 16:26:57,1,1.52,8.0,1.00,0.0,13.30,yellow,credit card,Lincoln Square East,Central Park,Manhattan,Manhattan

In [ ]:
df['color'].isnull()

0       False
1       False
2       False
3       False
4       False
        ...
6428    False
6429    False
6430    False
6431    False
6432    False
Name: color, Length: 6433, dtype: bool

In [ ]:
df['color'].isnull().sum()

0

In [ ]:
df['payment'].isnull().sum()

44

In [ ]:
df.isnull().sum()

pickup              0
dropoff             0
passengers          0
distance            0
fare                0
tip                 0
tolls               0
total               0
color               0
payment            44
pickup_zone        26
dropoff_zone       45
pickup_borough     26
dropoff_borough    45
dtype: int64

In [ ]:
(44/6433)*100

0.6839732628633608

In [ ]:
df.isnull().sum()/6433

pickup             0.000000
dropoff            0.000000
passengers         0.000000
distance           0.000000
fare               0.000000
tip                0.000000
tolls              0.000000
total              0.000000
color              0.000000
payment            0.006840
pickup_zone        0.004042
dropoff_zone       0.006995
pickup_borough     0.004042
dropoff_borough    0.006995
dtype: float64

In [ ]:
(df.isnull().sum()/df.shape[0])*100

pickup             0.000000
dropoff            0.000000
passengers         0.000000
distance           0.000000
fare               0.000000
tip                0.000000
tolls              0.000000
total              0.000000
color              0.000000
payment            0.683973
pickup_zone        0.404166
dropoff_zone       0.699518
pickup_borough     0.404166
dropoff_borough    0.699518
dtype: float64

In [ ]:
df.drop('pickup_zone',axis=1)

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Yorkville West,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6428,2019-03-31 09:51:53,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,6.36,green,credit card,Central Harlem North,Manhattan,Manhattan
6429,2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,58.80,green,credit card,East Concourse/Concourse Village,Queens,Bronx
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.0,0.00,0.0,17.30,green,cash,Bushwick North,Brooklyn,Brooklyn
6431,2019-03-04 10:09:25,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,6.80,green,credit card,East Flatbush/Remsen Village,Brooklyn,Brooklyn
6432,2019-03-13 19:31:22,2019-03-13 19:48:02,1,3.85,15.0,3.36,0.0,20.16,green,credit card,Windsor Terrace,Brooklyn,Brooklyn

In [ ]:
df.drop([2,3,6430],axis=0) #axis=0 for deleting row,axis=1 for deleting the column

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan
5,2019-03-11 10:37:23,2019-03-11 10:47:31,1,0.49,7.5,2.16,0.0,12.96,yellow,credit card,Times Sq/Theatre District,Midtown East,Manhattan,Manhattan
6,2019-03-26 21:07:31,2019-03-26 21:17:29,1,3.65,13.0,2.00,0.0,18.80,yellow,credit card,Battery Park City,Two Bridges/Seward Park,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6427,2019-03-23 18:26:09,2019-03-23 18:49:12,1,7.07,20.0,0.00,0.0,20.00,green,cash,Parkchester,East Harlem South,Bronx,Manhattan
6428,2019-03-31 09:51:53,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,6.36,green,credit card,East Harlem North,Central Harlem North,Manhattan,Manhattan
6429,2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,58.80,green,credit card,Jamaica,East Concourse/Concourse Village,Queens,Bronx
6431,2019-03-04 10:09:25,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,6.80,green,credit card,East New York,East Flatbush/Remsen Village,Brooklyn,Brooklyn
6432,2019-03-13 19:31:22,2019-03-13 19:48:02,1,3.85,15.0,3.36,0.0,20.16,green,credit card,Boerum Hill,Windsor Terrace,Brooklyn,Brooklyn